
export interface IconData {
  id: string;
  name: string;
  category: string;
  svgPath: string;
  isSelected?: boolean;
  /** True for icons generated by AI synthesis */
  isSynthesized?: boolean;
}

export interface IconAiMetadata {
  tags: string[];
  description: string;
}

export type ViewportSize = 16 | 24 | 32;
export type Weighting = 'regular' | 'medium' | 'bold';
export type TabType = 'grid' | 'list' | 'playground' | 'generator';
export type ViewMode = 'grid' | 'list';
export type AppTheme = 'dark' | 'light' | 'system';

export interface Collection {
  id: string;
  name: string;
  iconIds: string[];
  createdAt: number;
}

export interface IconTransform {
  rotate: number;
  scale: number;
  flipH: boolean;
  flipV: boolean;
}

export type AIProviderId = 'google' | 'openai' | 'anthropic' | 'local';

export type AIStatus = 'connected' | 'invalid' | 'missing' | 'rate-limited';

export interface AIProviderConfig {
  id: AIProviderId;
  apiKey: string;
  enabled: boolean;
  status: AIStatus;
  primaryModel: string;
  advancedModel: string;
}


export interface AppSettings {
  showGrid: boolean;
  gridOpacity: number;
  uiDensity: 'compact' | 'standard';
  autoExportFolders: boolean;
  primaryFont: string;
  monoFont: string;
  semanticSearchEnabled: boolean;
  aiEnabled: boolean;
  namingValidationEnabled: boolean;
  hasSeenAiPrompt: boolean;
  activeProvider: AIProviderId;
  providers: Record<AIProviderId, AIProviderConfig>;
}

export type ExportFormat = 'svg' | 'png' | 'jsx' | 'json';

export interface ExportOptions {
  format: ExportFormat;
  scale?: number; // for PNG export (1, 2, 4)
  includeBackground?: boolean;
}
